version: '3'
services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: mongo
        depends_on:
            - mongo
    consumer:
        build: ./consumer
        environment:
            KAFKA_BROKER_URL: broker:9092
            KAFKA_TOPIC: streaming.tweets
            ANGER_TOPIC: tweets.anger
            JOY_TOPIC: tweets.joy
            OPTIMISM_TOPIC: tweets.optimism
            SADNESS_TOPIC: tweets.sad
        ports:
            - 5000:5000
    stream_producer:
        build: ./stream_producer
        environment:
            KAFKA_BROKER_URL: broker:9092
            KAFKA_TOPIC: streaming.tweets
        depends_on:
            - consumer
networks: 
    default:
        external: 
            name: kafka-network
    mongonet:
        driver: bridge
volumes:
    mongodb: