version: '3'
services:
    stream_producer:
        build: ./stream_producer
        environment:
            KAFKA_BROKER_URL: broker:9092
            KAFKA_TOPIC: streaming.tweets
    consumer:
        build: ./consumer
        environment:
            KAFKA_BROKER_URL: broker:9092
            KAFKA_TOPIC: streaming.tweets
            ANGER_TOPIC: tweets.anger
            JOY_TOPIC: tweets.joy
            OPTIMISM_TOPIC: tweets.optimism
            SADNESS_TOPIC: tweets.sad
    
networks: 
    default:
        external: 
            name: kafka-network